In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,SCORERS

In [2]:
data=pd.read_csv("D:\\Workshops\\Python for Data Science Comprehensive Workshop\\Part 04 - Machine Learning\\Datasets\\Boston.CSV")
data.head()

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

# Creating K-Fold Corss Validation object with 5 folds. You can use any number of folds

In [4]:
kf=KFold(n_splits=5,shuffle=True)
kf

KFold(n_splits=5, random_state=None, shuffle=True)

In [5]:
model=LinearRegression()
model

LinearRegression()

# Split function is used to separet the training and testing data in each fold

In [6]:
kf.split(data) #This returns the indexes of training & testing data for each fold

In [7]:
list(kf.split(data))

[(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  12,  15,  17,
          20,  21,  22,  24,  25,  26,  27,  28,  29,  30,  31,  32,  34,
          35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  61,
          63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
          76,  77,  78,  79,  80,  81,  82,  83,  85,  87,  91,  92,  93,
          94,  95,  96,  97,  98,  99, 101, 102, 103, 104, 105, 106, 107,
         108, 109, 110, 112, 113, 114, 115, 116, 118, 119, 121, 122, 123,
         124, 125, 126, 127, 128, 129, 131, 132, 133, 134, 135, 136, 137,
         138, 140, 141, 142, 144, 145, 146, 147, 148, 149, 150, 151, 153,
         154, 155, 156, 159, 160, 161, 162, 164, 165, 166, 167, 168, 169,
         170, 171, 172, 173, 175, 176, 177, 179, 181, 182, 183, 184, 185,
         186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198,
         199, 200, 201, 202, 203, 206, 207, 210, 213, 214, 216, 218, 220,
         221, 222, 223, 224, 225, 226, 227, 228, 230, 231, 232, 233, 234,
         235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 249,
         250, 252, 254, 255, 256, 257, 258, 259, 260, 261, 262, 264, 265,
         268, 269, 271, 272, 273, 274, 276, 277, 278, 280, 281, 283, 284,
         285, 286, 289, 292, 293, 294, 297, 299, 300, 301, 302, 304, 305,
         310, 311, 312, 313, 314, 315, 316, 317, 319, 320, 321, 322, 323,
         324, 325, 326, 327, 329, 330, 331, 332, 333, 334, 335, 336, 338,
         339, 340, 341, 343, 344, 345, 346, 348, 351, 352, 353, 354, 355,
         356, 358, 359, 360, 361, 362, 363, 364, 365, 367, 368, 369, 371,
         372, 373, 375, 376, 377, 378, 379, 381, 382, 384, 385, 386, 387,
         388, 389, 391, 392, 393, 394, 396, 397, 399, 400, 401, 402, 403,
         404, 406, 407, 408, 412, 413, 414, 415, 418, 419, 421, 424, 425,
         426, 427, 428, 429, 430, 432, 433, 434, 435, 436, 437, 438, 439,
         440, 441, 442, 444, 445, 446, 447, 448, 449, 450, 452, 454, 455,
         456, 457, 458, 459, 460, 461, 462, 463, 465, 466, 467, 469, 470,
         472, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 486,
         487, 488, 489, 490, 492, 494, 496, 497, 498, 499, 500, 501, 502,
         503]),
  array([ 10,  11,  13,  14,  16,  18,  19,  23,  33,  60,  62,  84,  86,
          88,  89,  90, 100, 111, 117, 120, 130, 139, 143, 152, 157, 158,
         163, 174, 178, 180, 204, 205, 208, 209, 211, 212, 215, 217, 219,
         229, 247, 248, 251, 253, 263, 266, 267, 270, 275, 279, 282, 287,
         288, 290, 291, 295, 296, 298, 303, 306, 307, 308, 309, 318, 328,
         337, 342, 347, 349, 350, 357, 366, 370, 374, 380, 383, 390, 395,
         398, 405, 409, 410, 411, 416, 417, 420, 422, 423, 431, 443, 451,
         453, 464, 468, 471, 473, 485, 491, 493, 495, 504, 505])),
 (array([  0,   1,   3,   5,   6,   7,   8,  10,  11,  12,  13,  14,  15,
          16,  18,  19,  20,  21,  23,  26,  27,  28,  29,  30,  32,  33,
          34,  35,  37,  38,  40,  41,  42,  43,  44,  45,  46,  47,  48,
          49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  60,  61,  62,
          63,  64,  65,  66,  67,  68,  70,  71,  72,  73,  74,  75,  76,
          77,  78,  79,  80,  81,  83,  84,  85,  86,  88,  89,  90,  91,
          92,  93,  94,  96,  97,  98, 100, 101, 102, 103, 104, 105, 106,
         108, 110, 111, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
         123, 125, 126, 128, 130, 133, 134, 135, 136, 137, 138, 139, 140,
         143, 145, 147, 149, 150, 151, 152, 154, 155, 156, 157, 158, 160,
         161, 162, 163, 164, 165, 166, 168, 169, 170, 171, 172, 173, 174,
         175, 178, 179, 180, 181, 182, 183, 186, 187, 188, 190, 192, 193,
         197, 198, 199, 200, 202, 203, 204, 205, 208, 209, 210, 211, 212,
         213, 215, 216, 217, 218, 219, 220, 222, 223, 224, 228, 229, 230,
         231, 232, 233, 234, 237, 238, 242, 244, 245, 246, 247, 248, 249,
         250, 251, 252, 253, 255, 256, 258, 259, 260, 261, 262, 263, 264,
         265, 266, 267, 269, 270, 271, 272, 273, 275, 277, 278, 279, 280,
         282, 283, 284, 286, 287, 288, 290, 291, 292, 293, 294, 295, 296,
         297, 298, 299, 300, 302, 303, 304, 305, 306, 307, 308, 309, 310,
         311, 312, 314, 315, 317, 318, 319, 320, 321, 323, 324, 325, 327,
         328, 329, 330, 331, 333, 334, 337, 338, 340, 341, 342, 343, 344,
         345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357,
         358, 359, 360, 361, 362, 364, 365, 366, 367, 369, 370, 372, 373,
         374, 375, 376, 377, 379, 380, 381, 382, 383, 384, 385, 387, 388,
         389, 390, 391, 392, 394, 395, 396, 397, 398, 401, 402, 403, 405,
         406, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 420,
         422, 423, 425, 426, 427, 428, 429, 430, 431, 432, 434, 435, 437,
         438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450,
         451, 452, 453, 454, 455, 456, 457, 459, 460, 461, 462, 463, 464,
         466, 467, 468, 469, 471, 472, 473, 477, 478, 479, 480, 482, 483,
         484, 485, 486, 488, 490, 491, 492, 493, 495, 498, 499, 501, 503,
         504, 505]),
  array([  2,   4,   9,  17,  22,  24,  25,  31,  36,  39,  59,  69,  82,
          87,  95,  99, 107, 109, 112, 124, 127, 129, 131, 132, 141, 142,
         144, 146, 148, 153, 159, 167, 176, 177, 184, 185, 189, 191, 194,
         195, 196, 201, 206, 207, 214, 221, 225, 226, 227, 235, 236, 239,
         240, 241, 243, 254, 257, 268, 274, 276, 281, 285, 289, 301, 313,
         316, 322, 326, 332, 335, 336, 339, 363, 368, 371, 378, 386, 393,
         399, 400, 404, 407, 419, 421, 424, 433, 436, 458, 465, 470, 474,
         475, 476, 481, 487, 489, 494, 496, 497, 500, 502])),
 (array([  1,   2,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18,  19,  20,  22,  23,  24,  25,  28,  31,  33,
          34,  36,  37,  38,  39,  40,  41,  42,  44,  45,  46,  47,  50,
          54,  57,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  74,  79,  81,  82,  83,  84,  85,  86,  87,  88,
          89,  90,  91,  92,  94,  95,  96,  99, 100, 101, 103, 104, 106,
         107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 120,
         122, 124, 125, 126, 127, 129, 130, 131, 132, 133, 135, 136, 137,
         139, 140, 141, 142, 143, 144, 145, 146, 148, 149, 152, 153, 154,
         155, 156, 157, 158, 159, 160, 161, 163, 164, 167, 169, 170, 172,
         174, 175, 176, 177, 178, 180, 182, 184, 185, 186, 187, 188, 189,
         190, 191, 192, 193, 194, 195, 196, 199, 200, 201, 204, 205, 206,
         207, 208, 209, 211, 212, 214, 215, 216, 217, 218, 219, 221, 222,
         223, 225, 226, 227, 228, 229, 230, 231, 233, 234, 235, 236, 238,
         239, 240, 241, 242, 243, 244, 247, 248, 250, 251, 252, 253, 254,
         255, 256, 257, 258, 260, 263, 264, 265, 266, 267, 268, 270, 271,
         272, 274, 275, 276, 277, 279, 280, 281, 282, 283, 284, 285, 287,
         288, 289, 290, 291, 294, 295, 296, 298, 299, 300, 301, 302, 303,
         305, 306, 307, 308, 309, 310, 313, 314, 315, 316, 317, 318, 319,
         320, 322, 323, 324, 325, 326, 327, 328, 331, 332, 333, 335, 336,
         337, 338, 339, 340, 342, 344, 345, 346, 347, 348, 349, 350, 351,
         352, 353, 354, 356, 357, 359, 360, 361, 362, 363, 364, 365, 366,
         367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 378, 379, 380,
         381, 382, 383, 384, 385, 386, 389, 390, 391, 392, 393, 394, 395,
         396, 398, 399, 400, 401, 402, 403, 404, 405, 407, 408, 409, 410,
         411, 412, 413, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424,
         425, 427, 428, 429, 430, 431, 432, 433, 435, 436, 437, 438, 439,
         440, 441, 442, 443, 445, 447, 448, 450, 451, 452, 453, 455, 456,
         457, 458, 459, 460, 462, 464, 465, 466, 467, 468, 469, 470, 471,
         472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 484, 485, 487,
         489, 491, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503,
         504, 505]),
  array([  0,   3,  21,  26,  27,  29,  30,  32,  35,  43,  48,  49,  51,
          52,  53,  55,  56,  58,  73,  75,  76,  77,  78,  80,  93,  97,
          98, 102, 105, 119, 121, 123, 128, 134, 138, 147, 150, 151, 162,
         165, 166, 168, 171, 173, 179, 181, 183, 197, 198, 202, 203, 210,
         213, 220, 224, 232, 237, 245, 246, 249, 259, 261, 262, 269, 273,
         278, 286, 292, 293, 297, 304, 311, 312, 321, 329, 330, 334, 341,
         343, 355, 358, 377, 387, 388, 397, 406, 414, 426, 434, 444, 446,
         449, 454, 461, 463, 482, 483, 486, 488, 490, 492])),
 (array([  0,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  13,  14,
          15,  16,  17,  18,  19,  21,  22,  23,  24,  25,  26,  27,  29,
          30,  31,  32,  33,  35,  36,  39,  41,  42,  43,  44,  45,  46,
          47,  48,  49,  51,  52,  53,  54,  55,  56,  58,  59,  60,  62,
          64,  66,  69,  70,  71,  73,  74,  75,  76,  77,  78,  80,  81,
          82,  83,  84,  86,  87,  88,  89,  90,  91,  93,  95,  97,  98,
          99, 100, 101, 102, 104, 105, 107, 108, 109, 110, 111, 112, 114,
         116, 117, 119, 120, 121, 122, 123, 124, 127, 128, 129, 130, 131,
         132, 133, 134, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
         146, 147, 148, 150, 151, 152, 153, 154, 157, 158, 159, 162, 163,
         164, 165, 166, 167, 168, 170, 171, 173, 174, 175, 176, 177, 178,
         179, 180, 181, 182, 183, 184, 185, 187, 188, 189, 190, 191, 193,
         194, 195, 196, 197, 198, 199, 201, 202, 203, 204, 205, 206, 207,
         208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 219, 220, 221,
         223, 224, 225, 226, 227, 228, 229, 231, 232, 235, 236, 237, 239,
         240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 251, 252, 253,
         254, 257, 259, 260, 261, 262, 263, 265, 266, 267, 268, 269, 270,
         271, 273, 274, 275, 276, 278, 279, 281, 282, 285, 286, 287, 288,
         289, 290, 291, 292, 293, 295, 296, 297, 298, 299, 300, 301, 302,
         303, 304, 306, 307, 308, 309, 311, 312, 313, 315, 316, 318, 321,
         322, 324, 326, 328, 329, 330, 332, 334, 335, 336, 337, 339, 340,
         341, 342, 343, 344, 346, 347, 348, 349, 350, 351, 354, 355, 357,
         358, 360, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372,
         373, 374, 376, 377, 378, 380, 383, 384, 385, 386, 387, 388, 389,
         390, 391, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403,
         404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416,
         417, 419, 420, 421, 422, 423, 424, 426, 430, 431, 433, 434, 436,
         437, 438, 439, 443, 444, 445, 446, 448, 449, 451, 452, 453, 454,
         457, 458, 459, 461, 462, 463, 464, 465, 466, 468, 470, 471, 473,
         474, 475, 476, 477, 478, 481, 482, 483, 485, 486, 487, 488, 489,
         490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 502, 503,
         504, 505]),
  array([  1,  12,  20,  28,  34,  37,  38,  40,  50,  57,  61,  63,  65,
          67,  68,  72,  79,  85,  92,  94,  96, 103, 106, 113, 115, 118,
         125, 126, 135, 149, 155, 156, 160, 161, 169, 172, 186, 192, 200,
         218, 222, 230, 233, 234, 238, 250, 255, 256, 258, 264, 272, 277,
         280, 283, 284, 294, 305, 310, 314, 317, 319, 320, 323, 325, 327,
         331, 333, 338, 345, 352, 353, 356, 359, 361, 375, 379, 381, 382,
         392, 418, 425, 427, 428, 429, 432, 435, 440, 441, 442, 447, 450,
         455, 456, 460, 467, 469, 472, 479, 480, 484, 501])),
 (array([  0,   1,   2,   3,   4,   9,  10,  11,  12,  13,  14,  16,  17,
          18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
          31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  43,  48,  49,
          50,  51,  52,  53,  55,  56,  57,  58,  59,  60,  61,  62,  63,
          65,  67,  68,  69,  72,  73,  75,  76,  77,  78,  79,  80,  82,
          84,  85,  86,  87,  88,  89,  90,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 102, 103, 105, 106, 107, 109, 111, 112, 113, 115,
         117, 118, 119, 120, 121, 123, 124, 125, 126, 127, 128, 129, 130,
         131, 132, 134, 135, 138, 139, 141, 142, 143, 144, 146, 147, 148,
         149, 150, 151, 152, 153, 155, 156, 157, 158, 159, 160, 161, 162,
         163, 165, 166, 167, 168, 169, 171, 172, 173, 174, 176, 177, 178,
         179, 180, 181, 183, 184, 185, 186, 189, 191, 192, 194, 195, 196,
         197, 198, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210,
         211, 212, 213, 214, 215, 217, 218, 219, 220, 221, 222, 224, 225,
         226, 227, 229, 230, 232, 233, 234, 235, 236, 237, 238, 239, 240,
         241, 243, 245, 246, 247, 248, 249, 250, 251, 253, 254, 255, 256,
         257, 258, 259, 261, 262, 263, 264, 266, 267, 268, 269, 270, 272,
         273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
         286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
         301, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314,
         316, 317, 318, 319, 320, 321, 322, 323, 325, 326, 327, 328, 329,
         330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 341, 342, 343,
         345, 347, 349, 350, 352, 353, 355, 356, 357, 358, 359, 361, 363,
         366, 368, 370, 371, 374, 375, 377, 378, 379, 380, 381, 382, 383,
         386, 387, 388, 390, 392, 393, 395, 397, 398, 399, 400, 404, 405,
         406, 407, 409, 410, 411, 414, 416, 417, 418, 419, 420, 421, 422,
         423, 424, 425, 426, 427, 428, 429, 431, 432, 433, 434, 435, 436,
         440, 441, 442, 443, 444, 446, 447, 449, 450, 451, 453, 454, 455,
         456, 458, 460, 461, 463, 464, 465, 467, 468, 469, 470, 471, 472,
         473, 474, 475, 476, 479, 480, 481, 482, 483, 484, 485, 486, 487,
         488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 500, 501, 502,
         504, 505]),
  array([  5,   6,   7,   8,  15,  41,  42,  44,  45,  46,  47,  54,  64,
          66,  70,  71,  74,  81,  83,  91, 101, 104, 108, 110, 114, 116,
         122, 133, 136, 137, 140, 145, 154, 164, 170, 175, 182, 187, 188,
         190, 193, 199, 216, 223, 228, 231, 242, 244, 252, 260, 265, 271,
         299, 300, 302, 315, 324, 340, 344, 346, 348, 351, 354, 360, 362,
         364, 365, 367, 369, 372, 373, 376, 384, 385, 389, 391, 394, 396,
         401, 402, 403, 408, 412, 413, 415, 430, 437, 438, 439, 445, 448,
         452, 457, 459, 462, 466, 477, 478, 498, 499, 503]))]

# Training the model with training set and validating with testing set in each fold and appending RMSE for each fold

In [8]:
RMSE=[]

for i in list(kf.split(data)):
    model.fit(x[i[0],:],y[i[0]])
    y_pred=model.predict(x[i[1],:])
    RMSE.append(np.sqrt(mean_squared_error(y_pred,y[i[1]])))

# Root Mean Squared Error with Cross Validation

In [9]:
np.mean(RMSE)

4.8488701704366886

# Cross Validation Score

In [10]:
model=LinearRegression()
model

LinearRegression()

In [11]:
ncvals=cross_val_score(model,x,y,cv=10,scoring="neg_mean_squared_error")

In [12]:
cvals=-ncvals

In [13]:
cvals

array([  9.17006701,  14.76188969,  11.78968809,  34.93168849,
        26.8851826 ,  19.52818886,  10.70555866, 171.48795123,
        35.0922184 ,  11.64765827])

# Checking the SCORERS

In [14]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])